package alive

type PromptCase struct {
	Input    string `json:"input"`
	Expected string `json:"expected"`
}

var DefaultPrompts = []PromptCase{
	{Input: "Sentiment: 'Great work today.' Label positive or negative.", Expected: "positive"},
	{Input: "Sentiment: 'The app crashed again.' Label positive or negative.", Expected: "negative"},
	{Input: "Tone: 'Please send the file.' Label formal or casual.", Expected: "formal"},
	{Input: "Tone: 'Can you grab coffee?' Label formal or casual.", Expected: "casual"},
	{Input: "Intent: 'Book a room for Friday.' Label travel or support.", Expected: "travel"},
	{Input: "Intent: 'My password reset failed.' Label travel or support.", Expected: "support"},
	{Input: "Priority: 'Server is down for all users.' Label low or high.", Expected: "high"},
	{Input: "Priority: 'Update the footer color.' Label low or high.", Expected: "low"},
	{Input: "Category: 'refund request' Label billing or shipping.", Expected: "billing"},
	{Input: "Category: 'tracking number missing' Label billing or shipping.", Expected: "shipping"},
	{Input: "Topic: 'quarterly revenue' Label finance or weather.", Expected: "finance"},
	{Input: "Topic: 'chance of rain' Label finance or weather.", Expected: "weather"},
	{Input: "Mood: 'I love this update.' Label happy or upset.", Expected: "happy"},
	{Input: "Mood: 'This delay is frustrating.' Label happy or upset.", Expected: "upset"},
	{Input: "Text type: 'Use a strong password.' Label advice or story.", Expected: "advice"},
	{Input: "Text type: 'Once upon a time...' Label advice or story.", Expected: "story"},
	{Input: "Channel: 'subject: invoice due' Label email or chat.", Expected: "email"},
	{Input: "Channel: 'lol see you soon' Label email or chat.", Expected: "chat"},
	{Input: "Audience: 'board meeting agenda' Label work or school.", Expected: "work"},
	{Input: "Audience: 'homework rubric' Label work or school.", Expected: "school"},
	{Input: "Extract city from 'Flight to Berlin at 9'.", Expected: "Berlin"},
	{Input: "Extract first name from 'Agent: Mira Chen'.", Expected: "Mira"},
	{Input: "Extract color from 'Paint code: blue'.", Expected: "blue"},
	{Input: "Extract size from 'Size=L'.", Expected: "L"},
	{Input: "Extract status from 'status: pending'.", Expected: "pending"},
	{Input: "Extract domain from 'user@example.com'.", Expected: "example.com"},
	{Input: "Extract file extension from 'report.pdf'.", Expected: "pdf"},
	{Input: "Extract month from 'Due: June 12'.", Expected: "June"},
	{Input: "Extract currency from 'Price: USD 19'.", Expected: "USD"},
	{Input: "Extract item from 'Order: tea x2'.", Expected: "tea"},
	{Input: "Extract quantity from 'Order: tea x2'.", Expected: "2"},
	{Input: "Extract code after ID in 'ID: A17'.", Expected: "A17"},
	{Input: "Extract first tag from '#bug #ui'.", Expected: "bug"},
	{Input: "Extract last word from 'small green box'.", Expected: "box"},
	{Input: "Extract number from 'room 204B'.", Expected: "204"},
	{Input: "Extract unit from 'Length: 12 cm'.", Expected: "cm"},
	{Input: "Extract weekday from 'Meet on Tuesday'.", Expected: "Tuesday"},
	{Input: "Extract product from 'SKU chair-42'.", Expected: "chair"},
	{Input: "Extract language code from 'lang=en'.", Expected: "en"},
	{Input: "Extract seat from 'Seat 14C'.", Expected: "14C"},
	{Input: "Rewrite 'cant' with apostrophe.", Expected: "can't"},
	{Input: "Expand ASAP in words.", Expected: "soon"},
	{Input: "Lowercase 'Project Plan'.", Expected: "project plan"},
	{Input: "Uppercase 'save draft'.", Expected: "SAVE DRAFT"},
	{Input: "Title case 'monthly report'.", Expected: "Monthly Report"},
	{Input: "Plural of 'box'.", Expected: "boxes"},
	{Input: "Singular of 'cities'.", Expected: "city"},
	{Input: "Past tense of 'plan'.", Expected: "planned"},
	{Input: "Present participle of 'run'.", Expected: "running"},
	{Input: "Correct typo 'recieve'.", Expected: "receive"},
	{Input: "Correct typo 'adress'.", Expected: "address"},
	{Input: "Fix grammar: 'She go to work.'", Expected: "goes"},
	{Input: "Fix grammar: 'They was late.'", Expected: "were"},
	{Input: "Shorten 'approximately' to a common abbreviation.", Expected: "approx"},
	{Input: "Convert 'do not' to a contraction.", Expected: "don't"},
	{Input: "Convert 'won't' to full form.", Expected: "will not"},
	{Input: "Remove extra spaces from 'red   blue'.", Expected: "red blue"},
	{Input: "Add hyphen to 'well known author'.", Expected: "well-known"},
	{Input: "Use the word for &: 'tea & milk'.", Expected: "and"},
	{Input: "Normalize 'E-mail' spelling.", Expected: "email"},
	{Input: "15 minutes after 09:00.", Expected: "09:15"},
	{Input: "2 hours after 13:00.", Expected: "15:00"},
	{Input: "3 days after Monday.", Expected: "Thursday"},
	{Input: "100 cm in meters.", Expected: "1"},
	{Input: "2 kg in grams.", Expected: "2000"},
	{Input: "5 USD plus 7 USD.", Expected: "12"},
	{Input: "20% of 50.", Expected: "10"},
	{Input: "Half of 18.", Expected: "9"},
	{Input: "Count words in 'quick red box'.", Expected: "3"},
	{Input: "Count letters in 'data'.", Expected: "4"},
	{Input: "Is 14 even or odd?", Expected: "even"},
	{Input: "Is 9 even or odd?", Expected: "odd"},
	{Input: "Larger number: 18 or 12.", Expected: "18"},
	{Input: "Smaller number: 4 or 11.", Expected: "4"},
	{Input: "Next number in 2,4,6.", Expected: "8"},
	{Input: "Letter before C in alphabet.", Expected: "B"},
	{Input: "Letter after G in alphabet.", Expected: "H"},
	{Input: "Roman numeral for 4.", Expected: "IV"},
	{Input: "Decimal value of IV.", Expected: "4"},
	{Input: "Binary of decimal 5.", Expected: "101"},
	{Input: "YAML key in 'name: Ana'.", Expected: "name"},
	{Input: "JSON-like value of a in {'a':3}.", Expected: "3"},
	{Input: "Markdown heading level for '## Title'.", Expected: "2"},
	{Input: "HTML tag name in '<h1>Title</h1>'.", Expected: "h1"},
	{Input: "File basename of '/tmp/report.txt'.", Expected: "report.txt"},
	{Input: "Directory of '/tmp/report.txt'.", Expected: "/tmp"},
	{Input: "URL scheme in 'https://example.com'.", Expected: "https"},
	{Input: "URL host in 'https://example.com/a'.", Expected: "example.com"},
	{Input: "MIME type for JSON.", Expected: "application/json"},
	{Input: "HTTP method to fetch a page.", Expected: "GET"},
	{Input: "HTTP status 404 means found or missing?", Expected: "missing"},
	{Input: "Boolean value of '5 > 3'.", Expected: "true"},
	{Input: "Boolean value of '2 > 9'.", Expected: "false"},
	{Input: "Pick valid email: 'a@b.com' or 'abc'.", Expected: "a@b.com"},
	{Input: "Pick valid date: '2026-06-29' or 'Juneish'.", Expected: "2026-06-29"},
	{Input: "Timezone offset '+08:00' valid or invalid?", Expected: "valid"},
	{Input: "Hex color '#ff0000' valid or invalid?", Expected: "valid"},
	{Input: "Hex color 'red-500' valid or invalid?", Expected: "invalid"},
	{Input: "Keyword from 'The server restarted'.", Expected: "server"},
	{Input: "Language of 'bonjour'.", Expected: "French"},
}
