package alive

type PromptCase struct {
	Input    string `json:"input"`
	Expected string `json:"expected"`
}

var DefaultPrompts = []PromptCase{
	{Input: "Say OK.", Expected: "OK"},
	{Input: "Reply yes.", Expected: "yes"},
	{Input: "Reply no.", Expected: "no"},
	{Input: "Say hello.", Expected: "hello"},
	{Input: "Say hi.", Expected: "hi"},
	{Input: "Return 1.", Expected: "1"},
	{Input: "Return 2.", Expected: "2"},
	{Input: "Return A.", Expected: "A"},
	{Input: "Return B.", Expected: "B"},
	{Input: "Echo cat.", Expected: "cat"},
	{Input: "Echo dog.", Expected: "dog"},
	{Input: "Echo red.", Expected: "red"},
	{Input: "Echo blue.", Expected: "blue"},
	{Input: "Echo green.", Expected: "green"},
	{Input: "Echo sun.", Expected: "sun"},
	{Input: "Echo moon.", Expected: "moon"},
	{Input: "Echo star.", Expected: "star"},
	{Input: "Echo sky.", Expected: "sky"},
	{Input: "Echo sea.", Expected: "sea"},
	{Input: "Echo tree.", Expected: "tree"},
	{Input: "What is 1+1?", Expected: "2"},
	{Input: "What is 2+2?", Expected: "4"},
	{Input: "What is 3+1?", Expected: "4"},
	{Input: "What is 5-2?", Expected: "3"},
	{Input: "What is 6-1?", Expected: "5"},
	{Input: "What is 2*3?", Expected: "6"},
	{Input: "What is 8/2?", Expected: "4"},
	{Input: "Lowercase ABC.", Expected: "abc"},
	{Input: "Uppercase abc.", Expected: "ABC"},
	{Input: "First letter of apple?", Expected: "a"},
	{Input: "Last letter of cat?", Expected: "t"},
	{Input: "Color of grass?", Expected: "green"},
	{Input: "Color of sky?", Expected: "blue"},
	{Input: "Opposite of hot?", Expected: "cold"},
	{Input: "Opposite of up?", Expected: "down"},
	{Input: "Opposite of left?", Expected: "right"},
	{Input: "Opposite of day?", Expected: "night"},
	{Input: "Complete: good ___", Expected: "morning"},
	{Input: "Complete: thank ___", Expected: "you"},
	{Input: "Complete: see ___", Expected: "you"},
	{Input: "Answer with zero.", Expected: "zero"},
	{Input: "Answer with one.", Expected: "one"},
	{Input: "Answer with two.", Expected: "two"},
	{Input: "Answer with three.", Expected: "three"},
	{Input: "Answer with four.", Expected: "four"},
	{Input: "Answer with five.", Expected: "five"},
	{Input: "Return true.", Expected: "true"},
	{Input: "Return false.", Expected: "false"},
	{Input: "Reply ping.", Expected: "ping"},
	{Input: "Reply pong.", Expected: "pong"},
	{Input: "Echo API.", Expected: "API"},
	{Input: "Echo CLI.", Expected: "CLI"},
	{Input: "Echo test.", Expected: "test"},
	{Input: "Echo alive.", Expected: "alive"},
	{Input: "Echo ready.", Expected: "ready"},
	{Input: "Echo done.", Expected: "done"},
	{Input: "Echo pass.", Expected: "pass"},
	{Input: "Echo fail.", Expected: "fail"},
	{Input: "Echo quick.", Expected: "quick"},
	{Input: "Echo short.", Expected: "short"},
	{Input: "Say apple.", Expected: "apple"},
	{Input: "Say banana.", Expected: "banana"},
	{Input: "Say orange.", Expected: "orange"},
	{Input: "Say grape.", Expected: "grape"},
	{Input: "Say lemon.", Expected: "lemon"},
	{Input: "Say lime.", Expected: "lime"},
	{Input: "Say peach.", Expected: "peach"},
	{Input: "Say pear.", Expected: "pear"},
	{Input: "Say plum.", Expected: "plum"},
	{Input: "Say melon.", Expected: "melon"},
	{Input: "One word: coffee.", Expected: "coffee"},
	{Input: "One word: tea.", Expected: "tea"},
	{Input: "One word: water.", Expected: "water"},
	{Input: "One word: milk.", Expected: "milk"},
	{Input: "One word: bread.", Expected: "bread"},
	{Input: "One word: rice.", Expected: "rice"},
	{Input: "One word: egg.", Expected: "egg"},
	{Input: "One word: fish.", Expected: "fish"},
	{Input: "One word: bird.", Expected: "bird"},
	{Input: "One word: book.", Expected: "book"},
	{Input: "Answer: Monday.", Expected: "Monday"},
	{Input: "Answer: Tuesday.", Expected: "Tuesday"},
	{Input: "Answer: June.", Expected: "June"},
	{Input: "Answer: July.", Expected: "July"},
	{Input: "Answer: north.", Expected: "north"},
	{Input: "Answer: south.", Expected: "south"},
	{Input: "Answer: east.", Expected: "east"},
	{Input: "Answer: west.", Expected: "west"},
	{Input: "Type x.", Expected: "x"},
	{Input: "Type y.", Expected: "y"},
	{Input: "Type z.", Expected: "z"},
	{Input: "Type 9.", Expected: "9"},
	{Input: "Type 10.", Expected: "10"},
	{Input: "Return OK now.", Expected: "OK"},
	{Input: "Return READY now.", Expected: "READY"},
	{Input: "Return ALIVE now.", Expected: "ALIVE"},
	{Input: "Return PASS now.", Expected: "PASS"},
	{Input: "Say thanks.", Expected: "thanks"},
	{Input: "Say welcome.", Expected: "welcome"},
	{Input: "Say bye.", Expected: "bye"},
}
